### PR TITLE
Add file extension and file size filter

### PR DESCRIPTION
**Pull request by Stevecaboose**
Issue 252

* Rework method to get file names to avoid recursion
* Add setting to specify file extensions to be selected
* Add setting to specify minimum file size to be selected

### CODE REVIEW

**Comment by Stevecaboose** [comment]
Also includes change in https://github.com/0x90d/videoduplicatefinder/pull/275

**Comment by 0x90d** [comment]
File extensions in settings should contain an example in tooltip. Its not clear if "mp4,avi" or "*.mp4,*.avi" or ".mp4,.avi".

File size in settings should explain if its byte or anything else. In your code I see you divide the file size by `1048576`. Where does this number come from?

Why do you catch `UnauthorizedAccessException` when we have set `IgnoreInaccessible = true`

Please don't use `var` and use the new `new()` Syntax instead.

Since `GetFiles` returns `IEnumerable<string>`, cant you just `yield return` the `IEnumerable<string>` instead of allocating a new array only to `yield return` each element then?

Also you create a new `FileInfo` class for each item, only to check for size. I would rather move that check to the place where we already create a new `FileInfo` for those, so we don't create them twice.

I haven't measured your code, did you? I expect it to be slower and allocate more. I like to see a benchmark. Some people run this against 100,000 files or more.

**Comment by Stevecaboose** [comment]
* I will update the tooltip
* I have already placed a "(MB)" in the settings window. Let me know if that should be changed to something else
* I added the Unauthorized exception from https://github.com/0x90d/videoduplicatefinder/pull/275
* I will make the rest of the changes, no problem
* I have not done any testing. I have a file set of test data that is about 12k files and 6.5 TB in size

**Comment by Stevecaboose** [comment]
I ran a benchmark with 12k files with the method that does the traversing

`// Validating benchmarks:
// ***** BenchmarkRunner: Start   *****
// ***** Found 2 benchmark(s) in total *****
// ***** Building 1 exe(s) in Parallel: Start   *****
// start dotnet restore  /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 /p:Deterministic=true /p:Optimize=true in C:\Users\Steve\source\repos\VideoDuplicateFinder_Benchmark\VideoDuplicateFinder_Benchmark\bin\Debug\net6.0\dc7980af-64c0-49ce-89d4-6984d458ba0f
// command took 1.21s and exited with 0
// start dotnet build -c Release  --no-restore /p:UseSharedCompilation=false /p:BuildInParallel=false /m:1 /p:Deterministic=true /p:Optimize=true in C:\Users\Steve\source\repos\VideoDuplicateFinder_Benchmark\VideoDuplicateFinder_Benchmark\bin\Debug\net6.0\dc7980af-64c0-49ce-89d4-6984d458ba0f
// command took 1.76s and exited with 0
// ***** Done, took 00:00:03 (3.07 sec)   *****
// Found 2 benchmarks:
//   Benchmarks.Recursive_FileTraverse: Job-KOAYAX(Platform=X64, Runtime=.NET 6.0)
//   Benchmarks.Non_Recursive_FileTraverse: Job-KOAYAX(Platform=X64, Runtime=.NET 6.0)

// **************************
// Benchmark: Benchmarks.Recursive_FileTraverse: Job-KOAYAX(Platform=X64, Runtime=.NET 6.0)
// *** Execute ***
// Launch: 1 / 1
// Execute: dotnet "dc7980af-64c0-49ce-89d4-6984d458ba0f.dll" --benchmarkName "VideoDuplicateFinder_Benchmark.Benchmarks.Recursive_FileTraverse" --job "Platform=X64, Runtime=.NET 6.0" --benchmarkId 0 in C:\Users\Steve\source\repos\VideoDuplicateFinder_Benchmark\VideoDuplicateFinder_Benchmark\bin\Debug\net6.0\dc7980af-64c0-49ce-89d4-6984d458ba0f\bin\Release\net6.0
// BeforeAnythingElse

// Benchmark Process Environment Information:
// Runtime=.NET 6.0.1 (6.0.121.56705), X64 RyuJIT
// GC=Concurrent Workstation
// Job: Job-YAEXUO(Platform=X64)

OverheadJitting  1: 1 op, 133700.00 ns, 133.7000 us/op
WorkloadJitting  1: 1 op, 20672867500.00 ns, 20.6729 s/op

WorkloadWarmup   1: 1 op, 5751247200.00 ns, 5.7512 s/op
WorkloadWarmup   2: 1 op, 5807290300.00 ns, 5.8073 s/op
WorkloadWarmup   3: 1 op, 5852818300.00 ns, 5.8528 s/op
WorkloadWarmup   4: 1 op, 5714370400.00 ns, 5.7144 s/op
WorkloadWarmup   5: 1 op, 6017845200.00 ns, 6.0178 s/op
WorkloadWarmup   6: 1 op, 5900612900.00 ns, 5.9006 s/op

// BeforeActualRun
WorkloadActual   1: 1 op, 5712110100.00 ns, 5.7121 s/op
WorkloadActual   2: 1 op, 5658491900.00 ns, 5.6585 s/op
WorkloadActual   3: 1 op, 5668154600.00 ns, 5.6682 s/op
WorkloadActual   4: 1 op, 5709227600.00 ns, 5.7092 s/op
WorkloadActual   5: 1 op, 5670969000.00 ns, 5.6710 s/op
WorkloadActual   6: 1 op, 5698733700.00 ns, 5.6987 s/op
WorkloadActual   7: 1 op, 5889879400.00 ns, 5.8899 s/op
WorkloadActual   8: 1 op, 5612566500.00 ns, 5.6126 s/op
WorkloadActual   9: 1 op, 5679714500.00 ns, 5.6797 s/op
WorkloadActual  10: 1 op, 5873371200.00 ns, 5.8734 s/op
WorkloadActual  11: 1 op, 5660021000.00 ns, 5.6600 s/op
WorkloadActual  12: 1 op, 5722383900.00 ns, 5.7224 s/op
WorkloadActual  13: 1 op, 5698949600.00 ns, 5.6989 s/op
WorkloadActual  14: 1 op, 5708835400.00 ns, 5.7088 s/op
WorkloadActual  15: 1 op, 5661156900.00 ns, 5.6612 s/op

// AfterActualRun
WorkloadResult   1: 1 op, 5712110100.00 ns, 5.7121 s/op
WorkloadResult   2: 1 op, 5658491900.00 ns, 5.6585 s/op
WorkloadResult   3: 1 op, 5668154600.00 ns, 5.6682 s/op
WorkloadResult   4: 1 op, 5709227600.00 ns, 5.7092 s/op
WorkloadResult   5: 1 op, 5670969000.00 ns, 5.6710 s/op
WorkloadResult   6: 1 op, 5698733700.00 ns, 5.6987 s/op
WorkloadResult   7: 1 op, 5612566500.00 ns, 5.6126 s/op
WorkloadResult   8: 1 op, 5679714500.00 ns, 5.6797 s/op
WorkloadResult   9: 1 op, 5660021000.00 ns, 5.6600 s/op
WorkloadResult  10: 1 op, 5722383900.00 ns, 5.7224 s/op
WorkloadResult  11: 1 op, 5698949600.00 ns, 5.6989 s/op
WorkloadResult  12: 1 op, 5708835400.00 ns, 5.7088 s/op
WorkloadResult  13: 1 op, 5661156900.00 ns, 5.6612 s/op
GC:  0 0 0 5932560 1
Threading:  0 0 1

// AfterAll
// Benchmark Process 3960 has exited with code 0.

Mean = 5.682 s, StdErr = 0.008 s (0.15%), N = 13, StdDev = 0.031 s
Min = 5.613 s, Q1 = 5.661 s, Median = 5.680 s, Q3 = 5.709 s, Max = 5.722 s
IQR = 0.048 s, LowerFence = 5.590 s, UpperFence = 5.780 s
ConfidenceInterval = [5.645 s; 5.718 s] (CI 99.9%), Margin = 0.037 s (0.64% of Mean)
Skewness = -0.59, Kurtosis = 2.52, MValue = 2

// **************************
// Benchmark: Benchmarks.Non_Recursive_FileTraverse: Job-KOAYAX(Platform=X64, Runtime=.NET 6.0)
// *** Execute ***
// Launch: 1 / 1
// Execute: dotnet "dc7980af-64c0-49ce-89d4-6984d458ba0f.dll" --benchmarkName "VideoDuplicateFinder_Benchmark.Benchmarks.Non_Recursive_FileTraverse" --job "Platform=X64, Runtime=.NET 6.0" --benchmarkId 1 in C:\Users\Steve\source\repos\VideoDuplicateFinder_Benchmark\VideoDuplicateFinder_Benchmark\bin\Debug\net6.0\dc7980af-64c0-49ce-89d4-6984d458ba0f\bin\Release\net6.0
// BeforeAnythingElse

// Benchmark Process Environment Information:
// Runtime=.NET 6.0.1 (6.0.121.56705), X64 RyuJIT
// GC=Concurrent Workstation
// Job: Job-WDSEKD(Platform=X64)

OverheadJitting  1: 1 op, 135900.00 ns, 135.9000 us/op
WorkloadJitting  1: 1 op, 5719975400.00 ns, 5.7200 s/op

WorkloadWarmup   1: 1 op, 5759475200.00 ns, 5.7595 s/op
WorkloadWarmup   2: 1 op, 5762626400.00 ns, 5.7626 s/op
WorkloadWarmup   3: 1 op, 5798017300.00 ns, 5.7980 s/op
WorkloadWarmup   4: 1 op, 5706719900.00 ns, 5.7067 s/op
WorkloadWarmup   5: 1 op, 5742859900.00 ns, 5.7429 s/op
WorkloadWarmup   6: 1 op, 5831328800.00 ns, 5.8313 s/op
WorkloadWarmup   7: 1 op, 5774362900.00 ns, 5.7744 s/op

// BeforeActualRun
WorkloadActual   1: 1 op, 6085603600.00 ns, 6.0856 s/op
WorkloadActual   2: 1 op, 5706012100.00 ns, 5.7060 s/op
WorkloadActual   3: 1 op, 5700276400.00 ns, 5.7003 s/op
WorkloadActual   4: 1 op, 5724784500.00 ns, 5.7248 s/op
WorkloadActual   5: 1 op, 5812053000.00 ns, 5.8121 s/op
WorkloadActual   6: 1 op, 5738083600.00 ns, 5.7381 s/op
WorkloadActual   7: 1 op, 5801187200.00 ns, 5.8012 s/op
WorkloadActual   8: 1 op, 5673981300.00 ns, 5.6740 s/op
WorkloadActual   9: 1 op, 5919064300.00 ns, 5.9191 s/op
WorkloadActual  10: 1 op, 5691667800.00 ns, 5.6917 s/op
WorkloadActual  11: 1 op, 5746000000.00 ns, 5.7460 s/op
WorkloadActual  12: 1 op, 5700873700.00 ns, 5.7009 s/op
WorkloadActual  13: 1 op, 5740818400.00 ns, 5.7408 s/op
WorkloadActual  14: 1 op, 5773600100.00 ns, 5.7736 s/op
WorkloadActual  15: 1 op, 5813401900.00 ns, 5.8134 s/op

// AfterActualRun
WorkloadResult   1: 1 op, 5706012100.00 ns, 5.7060 s/op
WorkloadResult   2: 1 op, 5700276400.00 ns, 5.7003 s/op
WorkloadResult   3: 1 op, 5724784500.00 ns, 5.7248 s/op
WorkloadResult   4: 1 op, 5812053000.00 ns, 5.8121 s/op
WorkloadResult   5: 1 op, 5738083600.00 ns, 5.7381 s/op
WorkloadResult   6: 1 op, 5801187200.00 ns, 5.8012 s/op
WorkloadResult   7: 1 op, 5673981300.00 ns, 5.6740 s/op
WorkloadResult   8: 1 op, 5919064300.00 ns, 5.9191 s/op
WorkloadResult   9: 1 op, 5691667800.00 ns, 5.6917 s/op
WorkloadResult  10: 1 op, 5746000000.00 ns, 5.7460 s/op
WorkloadResult  11: 1 op, 5700873700.00 ns, 5.7009 s/op
WorkloadResult  12: 1 op, 5740818400.00 ns, 5.7408 s/op
WorkloadResult  13: 1 op, 5773600100.00 ns, 5.7736 s/op
WorkloadResult  14: 1 op, 5813401900.00 ns, 5.8134 s/op
GC:  0 0 0 15606344 1
Threading:  0 0 1

// AfterAll
// Benchmark Process 14148 has exited with code 0.

Mean = 5.753 s, StdErr = 0.018 s (0.31%), N = 14, StdDev = 0.066 s
Min = 5.674 s, Q1 = 5.702 s, Median = 5.739 s, Q3 = 5.794 s, Max = 5.919 s
IQR = 0.092 s, LowerFence = 5.564 s, UpperFence = 5.932 s
ConfidenceInterval = [5.679 s; 5.827 s] (CI 99.9%), Margin = 0.074 s (1.29% of Mean)
Skewness = 1, Kurtosis = 3.29, MValue = 2

// ***** BenchmarkRunner: Finish  *****

// * Export *
  BenchmarkDotNet.Artifacts\results\VideoDuplicateFinder_Benchmark.Benchmarks-report.csv
  BenchmarkDotNet.Artifacts\results\VideoDuplicateFinder_Benchmark.Benchmarks-report.html

// * Detailed results *
Benchmarks.Recursive_FileTraverse: Job-KOAYAX(Platform=X64, Runtime=.NET 6.0)
Runtime = .NET 6.0.1 (6.0.121.56705), X64 RyuJIT; GC = Concurrent Workstation
Mean = 5.682 s, StdErr = 0.008 s (0.15%), N = 13, StdDev = 0.031 s
Min = 5.613 s, Q1 = 5.661 s, Median = 5.680 s, Q3 = 5.709 s, Max = 5.722 s
IQR = 0.048 s, LowerFence = 5.590 s, UpperFence = 5.780 s
ConfidenceInterval = [5.645 s; 5.718 s] (CI 99.9%), Margin = 0.037 s (0.64% of Mean)
Skewness = -0.59, Kurtosis = 2.52, MValue = 2
-------------------- Histogram --------------------
[5.612 s ; 5.726 s) | @@@@@@@@@@@@@
---------------------------------------------------

Benchmarks.Non_Recursive_FileTraverse: Job-KOAYAX(Platform=X64, Runtime=.NET 6.0)
Runtime = .NET 6.0.1 (6.0.121.56705), X64 RyuJIT; GC = Concurrent Workstation
Mean = 5.753 s, StdErr = 0.018 s (0.31%), N = 14, StdDev = 0.066 s
Min = 5.674 s, Q1 = 5.702 s, Median = 5.739 s, Q3 = 5.794 s, Max = 5.919 s
IQR = 0.092 s, LowerFence = 5.564 s, UpperFence = 5.932 s
ConfidenceInterval = [5.679 s; 5.827 s] (CI 99.9%), Margin = 0.074 s (1.29% of Mean)
Skewness = 1, Kurtosis = 3.29, MValue = 2
-------------------- Histogram --------------------
[5.662 s ; 5.955 s) | @@@@@@@@@@@@@@
---------------------------------------------------

// * Summary *

BenchmarkDotNet=v0.13.1, OS=Windows 10.0.22000
AMD Ryzen 9 5950X, 1 CPU, 6 logical and 6 physical cores
.NET SDK=6.0.101
  [Host]     : .NET 6.0.1 (6.0.121.56705), X64 RyuJIT  [AttachedDebugger]
  Job-KOAYAX : .NET 6.0.1 (6.0.121.56705), X64 RyuJIT

Platform=X64  Runtime=.NET 6.0

|                     Method |    Mean |    Error |   StdDev | Ratio | Allocated |
|--------------------------- |--------:|---------:|---------:|------:|----------:|
|     Recursive_FileTraverse | 5.682 s | 0.0365 s | 0.0305 s |  1.00 |      6 MB |
| Non_Recursive_FileTraverse | 5.753 s | 0.0743 s | 0.0659 s |  1.01 |     15 MB |

// * Warnings *
Environment
  Summary -> Benchmark was executed with attached debugger

// * Hints *
Outliers
  Benchmarks.Recursive_FileTraverse: Platform=X64, Runtime=.NET 6.0     -> 2 outliers were removed (5.87 s, 5.89 s)
  Benchmarks.Non_Recursive_FileTraverse: Platform=X64, Runtime=.NET 6.0 -> 1 outlier  was  removed (6.09 s)

// * Legends *
  Mean      : Arithmetic mean of all measurements
  Error     : Half of 99.9% confidence interval
  StdDev    : Standard deviation of all measurements
  Ratio     : Mean of the ratio distribution ([Current]/[Baseline])
  Allocated : Allocated memory per single operation (managed only, inclusive, 1KB = 1024B)
  1 s       : 1 Second (1 sec)

// * Diagnostic Output - MemoryDiagnoser *


// ***** BenchmarkRunner: End *****
// ** Remained 0 benchmark(s) to run **
Run time: 00:04:46 (286.56 sec), executed benchmarks: 2

Global total time: 00:04:49 (289.63 sec), executed benchmarks: 2
// * Artifacts cleanup *
`

**Comment by 0x90d** [comment]
I've ran your `GetFiles` on a large collection to see how it performs. And I've noticed your function returns less (Count = `89,743`) result than mine (Count = `91,165`). Although exactly the same parameters were used. It turns out your function is not including files with extension in upper format, i.e. `my video.MP4`

**Comment by Stevecaboose** [comment]
Yeah now that you brought that up, I can see why its doing that. Ive been struggling to successfully implement validation through this UI framework (which im new to but learning). Do you have any resources to help me? Ive added the validation rule but I dont see a validation error show up on the UI.

**Comment by 0x90d** [comment]
Based on your PR I've improved the performance of file enumeration on latest commit. This now has caused conflicts with your PR. I think that the implementation of file extension, file sizes etc should be more robust and user friendly. I.e. giving them all extensions VDF supports as a list to choose from. For file sizes I would rather like to see more fine tuning so a user could for example define: "Size > X && Size < Y". I'm not fully sure myself whats the best implementation for this. The GUI aspect can be heavy and requires a lot of work. Or we use the expression builder that is rather cheap to implement but not everyone is familar with the C# syntax....

**Comment by Stevecaboose** [comment]
Sounds good this makes sense. I can experiment with a more userfriendly implementation for picking file extensions and file sizes

**Pull request closed without merging**
