### PR TITLE
Console version did not set exclude folders

### PR DESCRIPTION
**Pull request by obs1dium**
Excluded folders were erroneously added to the list of included folders

### CODE REVIEW

**Comment by matthewstrasiotto** [comment]
Hi there! Great PR, though it seems as though you've included your work from #117 

I'd love it if you could raise this against my fork https://github.com/matthewstrasiotto/videoduplicatefinder/issues/5 , but if you could tidy up the commits (Remove [e6ba99](https://github.com/0x90d/videoduplicatefinder/pull/116/commits/e6ba998bec0ac83b537b2824487caf4db0eb1e7f) ) in the branch you submit the PR from, so you can submit that fix separately, that'd be awesome. 

(To do this, you can checkout a new branch, interactively rebase & drop the commit, & raise the PR from that branch)
```bash
# from obs1dium/master
git checkout -b console_exclude_fix
git rebase -i e6ba998~
# Change e6ba998's "pick" to "drop", or just delete the line with "fix log display"
# Push as new branch named "console_exclude_fix"
git push -u origin HEAD
```

Raise the PR from obs1dium/console_exclude_fix :smile:

**Comment by vsolina2** [comment]
Thank you for taking over this project
Just a quick question the Binaries releases at the bottom of your page point to 0x90d releases will this be changed (Apologies if this is a silly question I’m still learning github )

**Comment by matthewstrasiotto** [comment]
@vsolina2 :
> Thank you for taking over this project Just a quick question the Binaries releases at the bottom of your page point to 0x90d releases will this be changed (Apologies if this is a silly question I’m still learning github )

That's not a silly question!

I haven't yet published any releases as I was planning on setting up some CI infrastructure beforehand - I'll push a quick release for the Windows & Linux builds after I merge some outstanding PRs from this project.

**Comment by obs1dium** [comment]
> Hi there! Great PR, though it seems as though you've included your work from #117
> 
> I'd love it if you could raise this against my fork [matthewstrasiotto/videoduplicatefinder#5](https://github.com/matthewstrasiotto/videoduplicatefinder/issues/5) , but if you could tidy up the commits (Remove [e6ba99](https://github.com/0x90d/videoduplicatefinder/pull/116/commits/e6ba998bec0ac83b537b2824487caf4db0eb1e7f) ) in the branch you submit the PR from, so you can submit that fix separately, that'd be awesome.

Hi. I'm quite busy at the moment, please feel free to just apply the changes in your branch, they're quite simple after all.

**Comment by matthewstrasiotto** [comment]
> > Hi there! Great PR, though it seems as though you've included your work from #117
> > I'd love it if you could raise this against my fork [matthewstrasiotto/videoduplicatefinder#5](https://github.com/matthewstrasiotto/videoduplicatefinder/issues/5) , but if you could tidy up the commits (Remove [e6ba99](https://github.com/0x90d/videoduplicatefinder/pull/116/commits/e6ba998bec0ac83b537b2824487caf4db0eb1e7f) ) in the branch you submit the PR from, so you can submit that fix separately, that'd be awesome.
> 
> Hi. I'm quite busy at the moment, please feel free to just apply the changes in your branch, they're quite simple after all.

Hey, that's actually what I just did 😄  sadly, because of some kind of hiccup in my git surgery, GitHub didn't give you a contributor credit on my repo. Let me know if you'd like to address this.

**Comment by matthewstrasiotto** [comment]
@vsolina2 hey - I've added a new release.
So far I've only build windows desktop, since the rest I can build & test on my linux machine. If you want to discuss this further, let's talk about it on my repo

 https://github.com/matthewstrasiotto/videoduplicatefinder/releases/tag/v2.0.8.9001

**Comment by obs1dium** [comment]
> Hey, that's actually what I just did 😄 sadly, because of some kind of hiccup in my git surgery, GitHub didn't give you a contributor credit on my repo. Let me know if you'd like to address this.

Don't worry about that :)

**Comment by vsolina2** [comment]
Thank you I’ll start testing it later today let me know when the Linux one is up as well
Also another user thefrank was working on a Mac version he did get it to work on the command line not in GUI I think you were in that conversation at some point. Maybe his work can be of help

**Comment by matthewstrasiotto** [comment]
> Thank you I’ll start testing it later today let me know when the Linux one is up as well

The linux build is available in the releases. I've tested it on Ubuntu20.04, & it seems to be working very well.

> Also another user thefrank was working on a Mac version he did get it to work on the command line not in GUI I think you were in that conversation at some point. Maybe his work can be of help

I've noticed his work, and since I'm able to build the Avalonia GUI against both Windows & Linux, it's very likely I can target OSX since OSX is much more similar to Linux anyway. 

Let's continue this discussion on [matthewstrasiotto/videoduplicatefinder](https://github.com/matthewstrasiotto/videoduplicatefinder), I don't want to bother @\obs1dium with a bunch of irrelevant pings.

**Comment by 0x90d** [comment]
Thanks for your contribution and sorry for not having this reviewed. Closing because this refers to outdated VDF Version 2

**Pull request closed without merging**
