### PR TITLE
Added macOS build script and console usage instructions

### PR DESCRIPTION
**Pull request by fixmk**
Looking for issue #130 I also tried to install UI version but got problems. I think that at least console version usage is worth mentioning for macOS.

Also added more explanation inside Markdown since me personally I was looking for usage examples and console arguments that this tool supports

### CODE REVIEW

**Comment by 0x90d** [comment]
Thanks for your contribution and sorry for not having this reviewed. Any chance you can update this so it works with my v3 commit?

**Comment by fixmk** [comment]
No worries! Let me resolve it on evening time

**Comment by fixmk** [comment]
My evening lasted for 2 weeks. My bad.

**Comment by 0x90d** [comment]
FYI: There are now auto builds for MacOS (see readme). So I'm closing this but still ❤ for your willing to contribute.

**Pull request closed without merging**
